.PHONY: tidy test run{{ if .modules.postgres.enabled }} docker-up docker-down{{ end }}

tidy:
	go mod tidy

test:
	go test -race ./...

run:
	go run ./cmd/api
docker-up:
	docker compose up --build

docker-down:
	docker compose down -v
